I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 67, in script call
    $ renpy.call(target_label)
  File "game/labels/location/lair.rpy", line 191, in script call
    call lb_create_treasures(True, 3)
  File "game/labels/location/lair.rpy", line 257, in script
    $ new_item = game.lair.treasury.craft(is_crafting=True, quality=['common'], price_multiplier=0, by_dragon=game.dragon.energy(), random_choice=random_choice)
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 67, in script call
    $ renpy.call(target_label)
  File "game/labels/location/lair.rpy", line 191, in script call
    call lb_create_treasures(True, 3)
  File "game/labels/location/lair.rpy", line 257, in script
    $ new_item = game.lair.treasury.craft(is_crafting=True, quality=['common'], price_multiplier=0, by_dragon=game.dragon.energy(), random_choice=random_choice)
  File "/home/g2/Games/DefilerWings/DefilerWings-1.4.1-all-noteat2/renpy/execution.py", line 52, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Linux-5.15.0-88-generic-x86_64-with-debian-bookworm-sid
Ren'Py 6.99.7.858
Defiler Wings 1.4.1.fdsc
